# Generated by Django 2.2.10 on 2020-05-29 13:01

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200528_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('task_id', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('dataset', models.TextField(default='')),
                ('comments', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_type', models.CharField(choices=[('Classification', 'Classification'), ('NamedEntityRecognition', 'Named Entity Recognition')], max_length=30)),
                ('status', models.CharField(max_length=100)),
                ('training_loss', django.contrib.postgres.fields.jsonb.JSONField()),
                ('total_training_time', models.TextField(default='')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.training_set+', to='contenttypes.ContentType')),
                ('users', models.ManyToManyField(related_name='trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
