# Generated by Django 2.2.10 on 2020-05-30 07:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='comments',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='training',
            name='total_training_time',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_loss',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
