# Generated by Django 2.2.10 on 2020-05-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200530_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='total_training_time',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
