# Generated by Django 2.2.10 on 2020-05-30 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20200530_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='user',
        ),
        migrations.AddField(
            model_name='training',
            name='users',
            field=models.ManyToManyField(related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
